jobs:
  docs:
    permissions:
      contents: read
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build --show-trace .#docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./result
      - uses: actions/deploy-pages@v4
"on":
  push:
    branches:
      - main
